### ISSUE TITLE
4.3. figrefがうまくいっていない部分がある

### ISSUE THREAD

**Issue by pocketberserker** [shinchoku-tairiku/book08#9]
そもそも画像じゃない説？

https://github.com/shinchoku-tairiku/book08/blob/1bb363e6c9595d186c4aea4ee1fd6101fc0868f5/src/youxkei/main.satyh#L199

👇 がPDFからキャプチャしたもの

![image](https://user-images.githubusercontent.com/911952/103146858-76459100-4792-11eb-9851-37cabbd456b7.png)

**Comment by amutake** [comment]
\coderef が正しそう
